name: estakhr_bagh_irani
description: Prototype Flutter app for "استخر باغ ایرانی" booking system.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  shamsi_date: ^1.1.0
  csv: ^5.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
